apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-db-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.database.postgresql.auth.password | b64enc | quote }}
  db-user: {{ .Values.database.postgresql.auth.username | b64enc | quote }}
  db-name: {{ .Values.database.postgresql.auth.database | b64enc | quote }}
  db-url: {{ printf "postgresql://%s:%s@%s-database:5432/%s" .Values.database.postgresql.auth.username .Values.database.postgresql.auth.password (include "todo-app.fullname" .) .Values.database.postgresql.auth.database | b64enc | quote }}