{{- if .Values.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-app.fullname" . }}-database-pvc
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {{- if .Values.global.storageClass }}
  {{- if (ne .Values.global.storageClass "") }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}